server:
  port: 8000

spring:
  profiles:
    active: dev
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: ${spring.profiles.active:dev}
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order