spring:
  cloud:
    openfeign:
      client:
        config:
          default: # 默认配置
            logger-level: full
            connect-timeout: 1000
            read-timeout: 2000
          service-product: # 指定服务名 @FeignClient("service-product")
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
#            request-interceptors: # openfeign 请求拦截器
#              - com.example.cloud.feign.interceptor.XTokenRequestInterceptor
#            retryer: feign.retryer.DefaultRetryer # 默认重拾机制

feign:
  sentinel:
    enabled: true # 开启sentinel
  fallback:
    enabled: true # 开启feign的fallback