spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods: "*"

      routes:
        - id: bing-route
          uri: https://cn.bing.com
          predicates:
            - name: Path
              args:
                pattern: /search
            - name: Query
              args:
                param: q
                regexp: haha
#            - Vip=user,leifengyang
            - name: Vip
              args:
                param: user
                value: leifengyang
          order: 10
          metadata:
            hello: world
        - id: order-route
          uri: lb://service-order
          predicates:
            - name: Path  #PathRoutePredicateFactory
              args:
                pattern: /api/order/**
                matchTrailingSlash: true
          filters: # /api/order/ab/c   /ab/c
          - RewritePath=/api/order/?(?<segment>.*),/$\{segment}
          - OnceToken=X-Response-Token,jwt # 自定义过滤器：一次性token
          order: 1
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/?(?<segment>.*),/$\{segment}
          order: 2
      default-filters:  # 默认过滤器
        - AddResponseHeader=X-Response-Abc,123