server:
  port: 9000

spring:
  profiles:
    active: dev
  application:
    name: service-product
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: ${spring.profiles.active:dev}
    sentinel:
      transport:
        dashboard: localhost:8080 # sentinel控制台地址
      eager: true
  config:
    import:
      - nacos:common.properties?group=product